server:
  port: 8080

spring:
  application:
    name: coc
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**

external:
  coc:
    api-key: ${COC_API_KEY}
    domain: https://api.clashofclans.com
    end-point:
      clans:
        prefix: /v1/clans
        clan-tag: /{clanTag}
        capital-raid-seasons: /{clanTag}/capitalraidseasons
        current-war: /{clanTag}/currentwar
