server:
  port: 8080

spring:
  application:
    name: coc

external:
  coc:
    api-key: ${COC_API_KEY}
    domain: https://api.clashofclans.com
    end-point:
      clans-clan-tag: /v1/clans/{clanTag}
